### ISSUE TITLE
hows it different to perkeep

### ISSUE THREAD

**Issue by allyraza** [upspin/upspin#588] opened 2018-05-06 10:10 UTC
Hi, I see brad fitzpatrick has also been working on a very similar project (perkeep) how is upspin different from perkeep.

**Comment by jzacsh** [comment] 2018-05-06 20:44
not an answer to your question, but relevant: #177 is to compare to other systems _(note: camlistore was perkeep's name when that bug was opened)_

**Comment by adg** [comment] 2018-05-07 00:33
Dupe of #177.

**Closed by adg** 2018-05-07 00:33 UTC
