### ISSUE TITLE
dir/server: record current root on flush

### ISSUE THREAD

**Issue by adg** [upspin/upspin#419] opened 2017-07-10 04:43 UTC
The current `dir/server` implementation stores logs locally, and so it only keeps track of tree root nodes on local disk. If a user loses that local disk for whatever reason it could be extremely difficult to locate the most recent root. We should fix this.

One way to address this issue is to provide a storage configuration to the dirserver, the same way we do for storeserver, and for the `dir/server` implementation to store the latest root entry—or a reference to it—there.

**Comment by adg** [comment] 2017-07-10 04:43
cc @edpin: does this sound like a reasonable approach to you?

**Comment by edpin** [comment] 2017-07-11 16:10
Duplicate of #393

**Closed by edpin** 2017-07-11 16:10 UTC

**Comment by adg** [comment] 2017-07-11 21:17
@edpin sure, but do you care to comment on #393? Or, if you don't care, I guess I should just do what I think makes sense.
