### ISSUE TITLE
double compressed download archive

### ISSUE THREAD

**Issue by srlehn** [upspin/upspin#637] opened 2020-04-20 11:16 UTC
The archive [upspin.linux_amd64.tar.gz](https://upspin.io/dl/upspin.linux_amd64.tar.gz) (24 Jan 20 at 22:54 UTC) from https://upspin.io/dl/ seems to be a .tar.gz.gz file.

**Comment by adg** [comment] 2020-04-20 22:46
What are you using to download it?

The HTTP response has `Content-Type: application/x-gzip`, so it is
technically gzipped twice, but the second layer should be transparent to
whatever downloads the file.

It's possible your HTTP client is broken, or that our HTTP server is
somehow misconfigured, but I'm unable to reproduce the issue here either
with Chrome, Safari, or curl.

**Comment by srlehn** [comment] 2020-04-22 14:10
I am using Firefox ESR 68.7.0esr (64-Bit) under Debian GNU/Linux 10. It does happen in a new profile. Not sure if i have a misconfiguration somewhere. Chromium and curl downloads are fine.

Accept.* request headers
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
```

response headers
```
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/x-gzip
Strict-Transport-Security: max-age=86400; includeSubDomains
Vary: Accept-Encoding
Date: ...
Transfer-Encoding: chunked
```

**Comment by adg** [comment] 2020-04-23 00:33
I just tried it in both Firefox 75.0 and 68.7.0esr and in both cases it
left a .tar.gz file in my Downloads directory, which appears to correctly
be a gzipped tar file (and only gzipped once).

Being unable to reproduce this here I'm not sure how to push this issue
forward. Perhaps someone reading this has a linux machine they could try
downloading from? (I'm on macOS here)

**Comment by colintedford** [comment] 2020-04-23 01:26
I got a single-compressed download using Firefox 72.01 on Linux Mint 
18.3. Same on an old Firefox 66.03 / Linux Mint 17.3 I have sitting 
around.

**Comment by adg** [comment] 2020-04-27 04:50
Being unable to reproduce this, I propose closing the issue. Any objections?

**Comment by mennis** [comment] 2021-01-24 07:13
This report may be related to this Mozilla [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1269101) .

**Closed** 2021-01-31 04:49 UTC
