### ISSUE TITLE
store: need a way to account for storage usage per user

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#315] opened 2017-03-07 21:49 UTC
Motivating factors:
- Shared or commercial systems may want to charge users per unit of data stored.
- Reclaiming space (garbage collection) may benefit from ease of locating per-user references.
- A console (as in issue #312) may benefit from reporting this information as well.

There are ways already to accomplish the accounting piece without changes now: set up different endpoints for each user, each being backed by a separate accounting unit -- different buckets in GCP, different directory or partition for an on-disk Store, etc. However, having the Store handle some of the burden may be beneficial even to alternate solutions.

**Comment by transitorykris** [comment] 2017-04-05 08:46
A related (and probably separate) problem is accounting for bytes transferred.

**Comment by adg** [comment] 2017-08-03 04:30
Duplicate of #138

**Closed by adg** 2017-08-03 04:30 UTC
Labels: feature
