### ISSUE TITLE
cmd/upspinfs: file permissions are enforced to 0700

### ISSUE THREAD

**Issue by stapelberg** [upspin/upspin#331] opened 2017-03-15 17:36 UTC
Writing a file to upspinfs results in that file showing up with 0644:
```
$ echo new > /up/michael@example.com/bleh
$ ls -l /up/michael@example.com/bleh
-rw-r--r-- 1 michael michael   4 2017-03-15 18:27 bleh
```

However, after remounting upspinfs, the permissions are reset to 0700:

```
$ fusermount -u /up
$ upspinfs /up &
$ ls -l /up/michael@example.com/bleh
-rwx------ 1 michael michael   4 2017-03-15 18:27 bleh
```

The same effect can be observed after trying to remove individual bits using e.g. `chmod u-w /up/michael@example.com/bleh` or `chmod u-x /up/michael@example.com/bleh`

I understand that it may not be possible to easily derive the read/write bits from upspin ACLs (or is it just not implemented?), but that doesn’t apply to the executable bit.

If this is working as intended, the fact that upspinfs happily seems to accept mode changes and then silently discards them when remounting is irritating.

**Comment by presotto** [comment] 2017-03-15 22:10
I just updated the doc.go for upspinfs this morning to explain it.  It is working as intended.  And no, that doesn't apply to the executable bit since setting it in unix is not the same as creating a file that might be executable.  And I'm not going to read every file from remote store just to figure out if it is executable when you stat.

It agree that it may be irritating.  I see two possible solutions neither of which I really like a lot:

1) add the permission bits to the ._<filename> file that MacOS and Linux use to save extended attributes.  It would have the aggravating effect of dropping junk all over the file system and increasing latency and network traffic but it would preserve some semantics.

2) change upspin.DirEntry yet again to add a blind field to be used for stuff like this.

Of course, I'm pretty happy with leaving it as is.  I could see it being a pain if you put "." in your $PATH.  Of course, if you do that, you are asking to be owned.

**Comment by stapelberg** [comment] 2017-03-17 07:45
Thanks for the explanation.

> And no, that doesn't apply to the executable bit since setting it in unix is not the same as creating a file that might be executable.

I don’t follow. What’s the difference between `chmod +x file` and `install -m 755 file`? (Or did you mean something else entirely?)

> Permission bits are settable but are not stored in Upspin.

What’s the rationale for this behavior as opposed to enforcing the permission to be 0700 at all times?

**Comment by presotto** [comment] 2017-03-18 17:48
On Fri, Mar 17, 2017 at 12:45 AM, Michael Stapelberg <
notifications@github.com> wrote:

> Thanks for the explanation.
>
> And no, that doesn't apply to the executable bit since setting it in unix
> is not the same as creating a file that might be executable.
>
> Your original message implied that I figure out the executable by looking
at the file.  However that also isn't correct since I can't tell what the
user's intent was, i.e., did he really want it to be execurable?  Granted,
in most cases he would.  Unfortunately, it would mean reading in files when
someone stat's them which does have performance implications.

> I don’t follow. What’s the difference between chmod +x file and install
> -m 755 file? (Or did you mean something else entirely?)
>
> Permission bits are settable but are not stored in Upspin.
>
> What’s the rationale for this behavior as opposed to enforcing the
> permission to be 0700 at all times?
>
I originally had it 0700 at all times and error'd if anyone tried to
chmod.  That broke all sorts of tools.  However, I could just say OK to
chmods and still leave things 0700.  I haven't tried that and it probably
makes more sense.

**Comment by stapelberg** [comment] 2017-03-18 18:01
> Your original message implied that I figure out the executable by looking at the file

Ah, sorry, I didn’t mean to imply that. I wanted to say that only read/write is covered by upspin ACLs, and executable status isn’t covered by upspin ACLs, so I would have expected it to be stored outside of the ACLs. I agree that it doesn’t make sense to look at file contents.

> I originally had it 0700 at all times and error'd if anyone tried to
> chmod.  That broke all sorts of tools.  However, I could just say OK to
> chmods and still leave things 0700.  I haven't tried that and it probably
> makes more sense.

Thanks for the context. FWIW, the `vfat` file system in Linux behaves the same way: it accepts chmods, but the file permissions don’t actually change:

```
$ ls -l /mnt/loop/cmdline.txt
-r-xr-xr-x 1 root root   89 2017-03-02 23:33 cmdline.txt
$ sudo chmod -x /mnt/loop/cmdline.txt
$ ls -l /mnt/loop/cmdline.txt
-r-xr-xr-x 1 root root   89 2017-03-02 23:33 cmdline.txt
```

So, yes, changing the behavior like that seems like a good idea :).

**Comment by robpike** [comment] 2017-04-03 22:21
This is now fixed as suggested.

**Closed by robpike** 2017-04-03 22:21 UTC
