### ISSUE TITLE
cmd/upspinfs: ls is slow

### ISSUE THREAD

**Issue by josselin-c** [upspin/upspin#549] opened 2017-11-29 14:18 UTC
On my Macbook, running `ls` in a directory with over 4000 pictures takes ~30s. I think this is quite slow.
My internet connection should be fast enough: 10MB/s, the data store is hosted on GCE.

Configuration:
```
username: me@me.fr
dirserver: remote,xxx.upspin.services:443
storeserver: remote,xxx.upspin.services:443
packing: ee
cache: localhost:8443
```

```
$ upspinfs --version
Build time: Nov 23 22:33:14 2017 UTC
Git hash:   b6cbee6f6dfe62ee7474db0dc25e0ed106cd4969
```

**Comment by kaervin** [comment] 2017-12-04 00:06
Activate caching. This is a duplicate of https://github.com/upspin/upspin/issues/543

As for why ls is so slow without caching I still don't quite understand, and I think it is not really clear to many users either that they should usually run the cacheserver.
Maybe enable the cacheserver by default, so that new users aren't exposed to slowness by default?

**Comment by josselin-c** [comment] 2017-12-04 09:03
If list the processes running on my machine I do have a cacheserver running:
```
$ ps xa | grep cache
 2614   ??  S      3:30.17 cacheserver -log=info
11558 s003  R+     0:00.00 grep cache
```
What about my configuration? Isn't `cache: localhost:8443` enough?

**Comment by presotto** [comment] 2017-12-21 20:56
Sorry I hadn't looked at this earlier. localhost:8443 should be good enough. 

cache: yes

would be better, uses a user domain socket. However the diff should not be 30 secs.  I'll try a 4k file sir today and see if there's some n squared thing going on.

**Comment by presotto** [comment] 2017-12-22 00:32
OK, ls goes fast enough, 1.6 seconds.  ls -l though takes 40 seconds on my system.  I fear FUSE may be the problem but I'll take a look. Doing the same using the upspin command takes .07 seconds.

**Comment by presotto** [comment] 2017-12-22 07:26
yup, i have an n squared problem.  Trying to figure out a solution.

**Closed** 2018-01-02 21:50 UTC
