### ISSUE TITLE
cacheserver/git problem

### ISSUE THREAD

**Issue by presotto** [upspin/upspin#557] opened 2017-12-14 22:46 UTC
Twice now, after restarting my system, git status has thought that I had removed all the files in my depot although I can still read them via upspinfs.  Clearly cacheserver related because after restarting it, git status was back to normal.  However this is a bit frightening. I'll keep trying to figure it out.

**Comment by idrarig** [comment] 2018-04-18 16:52
I think I'm experiencing a similar problem with any program that writes a file and expects to be able to read it back soon after (like git does). The most recent unhappy incident: I was using mutt, trying to keep my mail in Maildir format in Upspin, and tried to postpone a message, which entails saving a file with the draft. My hunch is that it tries to confirm the write (or something) by reading it back, and if that fails, it tries to save again. I ended up with ~20,000 copies of the same draft (the time it took me to give up and kill mutt, not having time for investigation at the moment). I can confirm it's the same file:

```
% ls -1 | head -100 | xargs sha1sum | cut -f1 -d' ' | uniq -c
5046: signal: sys: write on closed pipe
    100 0d2be36f2f0347ae43c705198ed0451606e0a3f5
```

I wonder if this and other issues will be fixed in one fell swoop by the implementation of disconnected operation.

Let me know if I should make a more useful investigation.

**Comment by presotto** [comment] 2018-04-18 17:08
If upspinfs has it, the read back is supposed to succeed immediately
thereafter since the cache behavior locally is synchronous.  The problem
with writebacks (which I apparently haven't fixed if someone is still
seeing it) is that the block won't be seen on another system but the one
that wrote it will have no problem.

So I am very interested in your problem because it looks like a semantic
failure in upspinfs, i.e., whatever mutt is expecting, upspinfs is not
providing.  I'm praying this is repeatable.  If so, could you run upspinfs
in debug mode while you do it and send me the debug output?

**Comment by presotto** [comment] 2018-04-18 17:09
If upspinfs has it, the read back is supposed to succeed immediately
thereafter since the cache behavior locally is synchronous.  The problem
with writebacks (which I apparently haven't fixed if someone is still
seeing it) is that the block won't be seen on another system but the one
that wrote it will have no problem.

So I am very interested in your problem because it looks like a semantic
failure in upspinfs, i.e., whatever mutt is expecting, upspinfs is not
providing.  I'm praying this is repeatable.  If so, could you run upspinfs
in debug mode while you do it and send me the debug output?

**Comment by idrarig** [comment] 2018-04-18 17:50
If you think you've fixed it, I think it's more likely that I have something wrong in my setup... I'll reproduce this as simply as possible, hopefully, with software versions. In any case the server is not one of the standard ones, I wonder if there's a chance that that's to blame? I have a tendency to assume the problem is on my end :D

**Comment by idrarig** [comment] 2018-04-18 18:46
The problem I was seeing has to do with comparing two links to the same file, so it's unrelated to this issue. My worklog with more information is at https://pastebin.com/raw/aZcyKQMJ to avoid spamming here with long messages.

**Comment by presotto** [comment] 2018-04-18 18:52
Ahh!  Thanks.  Our hard links are not semantically equivalent to posix ones
since I have to fake them, so to speak, that is, I have two directory
entries pointing to the same blocks but they won't look exactly like posix
links.  I see your worklog.  Does the strace show more of the stat buffer
returned than ...?  If I can figure out what it sees that is different
perhaps I can hack a fix.

**Comment by presotto** [comment] 2018-04-18 19:41
Looking at mutts' safe_rename, if I make the link() actually fail with
ENOSYS or ENOTSUP it should work. Unfortunately, I think that will break
git but I can test that easily enough.

**Comment by idrarig** [comment] 2018-04-18 19:44
Yeah, and this is the comparison, you no doubt have already found it as you're looking here as well... https://gitlab.com/muttmua/mutt/blob/master/lib.c#L388

**Comment by presotto** [comment] 2018-04-18 20:02
I could make the I odd be the hash of the block references.  Then the
comparison would work.  However I'm a bit afraid of the kernel then getting
confused in some untestable way.  I'll start by making hard links
unsupported and see if that breaks anything else.

**Comment by idrarig** [comment] 2018-04-20 10:15
Making hard links unsupported sounds reasonable to me, not for this specific problem, but in general:
I think either the semantics for the operation are respected (e.g., equal inodes in this case, if I understand correctly) or support for it is dropped, but that's just my two cents! On the other hand, I understand you don't want to break your usage of git repositories within Upspin :) (Never mind about my usage of mutt/Maildir in concert with Upspin; it's okay if it turns out not to be possible. I'm merely exploring various possibilities with Upspin, trying to get most of my stuff on it.)

Thanks for your help here!

**Comment by presotto** [comment] 2018-04-25 20:28
Making hard links return ENOTSUP in upspinfs doesn't break git, at least at
first blush.

Now I have to decide if it is the right thing to do.  Until now ln created
a new DirEntry that pointed to the same content as the old one.  This make
our hard link essentially a copy on write.  Anything that looked under the
covers, for example at the inode number, would discover that something was
amiss.  Ditto any changes to one file name, either in permissions or
content, would not be reflected in the other.

I could hack a change that would cause upspinfs to return the same inode
number for both file names (for example by making the inode a hash of the
blocks).  This would fix immediate problems (the safe rename check in mutt)
but would still leave the underlying problem of the semantics not matching
the semantics in a Unix/Linux fs. My main fear is that my deviating from
the expected semantics could cause bad and hard to debug surprises in the
future.

So, I'm asking the community.  Does anyone know what making hard links
return ENOTSUP would break? Unless I hear vociferous requests not to do it,
I will start returning ENOTSUP.  Git and mutt and mv all are happy with
that.

**Closed** 2018-05-02 19:50 UTC
