### ISSUE TITLE
serverutil/perm: should Perm be a wrapper?

### ISSUE THREAD

**Issue by edpin** [upspin/upspin#353] opened 2017-03-30 22:34 UTC
Perm as a wrapper has one interesting property: it works on any DirServer and any Store implementation.

However, it also has costs:
- It now has channels to synchronize the start, since the wrapping happens while the servers are starting.
- It has quite a bit of internal state that needs to be set up and checked for testing, which is not ideal.
- The tests have races, due to the racy nature of starting Perm.
- It adds an indirection to every call to the Dir and Store interfaces.

The interesting property above of working with inprocess as well as the server versions does not seem like enough justification to me to have a costly wrapper. Perm should be made a simple object that can be trivially added to Delete and Put in the right places in all implementations. That's the same approach we used with Glob -- set it up and just call it in the right place, why not Perm?

Just my two cents.

Thoughts?

**Comment by adg** [comment] 2017-04-03 22:31
> It now has channels to synchronize the start, since the wrapping happens while the servers are starting.

It has a channel to tell it when to start, which is fine and works well. Not sure what the issue is here.

> It has quite a bit of internal state that needs to be set up and checked for testing, which is not ideal.

I'm not sure what you're referring to, but IMO [there is barely anything to serverutil/perm at all](https://upspin.googlesource.com/upspin/+/master/serverutil/perm/perm.go). Any re-implementation elsewhere would still have a loop that watches a dirserver, etc. That's the only really interesting piece of the code. The rest is just a few wrappers. 

> The tests have races, due to the racy nature of starting Perm.

I think the tests just have to be adjusted to actually wait for the right things to happen. But nobody has really investigated those test failures.

I suspect if we actually use the ready channel in the tests we might get somewhere (at the moment we just pass it a closed channel so that it starts right away).

> It adds an indirection to every call to the Dir and Store interfaces.

This is not relevant. However this is implemented there will be a function call somewhere.

**Comment by adg** [comment] 2017-04-03 22:56
Before doing any rearchitecting I'd prefer to understand why the tests generate all these log messages:

```
2017/04/03 22:54:26.018901 dir/server/tree.logOffsetsFor: mkdir /var/folders/2r/2wscqnf957d_75ltvpj_n4zc0035qk/T/testenv-dirserver889540723/d.tree.log.aly@example.com: no such file or directory
2017/04/03 22:54:26.018950 dir/server/tree.logOffsetsFor: mkdir /var/folders/2r/2wscqnf957d_75ltvpj_n4zc0035qk/T/testenv-dirserver249364790/d.tree.log.aly@example.com: no such file or directory
2017/04/03 22:54:26.018914 dir/server/tree.logOffsetsFor: mkdir /var/folders/2r/2wscqnf957d_75ltvpj_n4zc0035qk/T/testenv-dirserver419507105/d.tree.log.aly@example.com: no such file or directory
2017/04/03 22:54:26.019071 newWithEnv: watch: dir/server.Watch: I/O error:
	dir/server/tree.Watch:
	dir/server/tree.NewReader: open /var/folders/2r/2wscqnf957d_75ltvpj_n4zc0035qk/T/testenv-dirserver249364790/d.tree.log.aly@example.com/0: no such file or directory
2017/04/03 22:54:26.019113 newWithEnv: watch: dir/server.Watch: I/O error:
	dir/server/tree.Watch:
	dir/server/tree.NewReader: open /var/folders/2r/2wscqnf957d_75ltvpj_n4zc0035qk/T/testenv-dirserver889540723/d.tree.log.aly@example.com/0: no such file or directory
2017/04/03 22:54:26.019165 newWithEnv: watch: dir/server.Watch: I/O error:
	dir/server/tree.Watch:
	dir/server/tree.NewReader: open /var/folders/2r/2wscqnf957d_75ltvpj_n4zc0035qk/T/testenv-dirserver419507105/d.tree.log.aly@example.com/0: no such file or directory
```

A client calling Watch shouldn't trigger these I/O errors, regardless of the state of dir/server.

**Comment by adg** [comment] 2017-04-25 06:20
I did a lot of work about a month ago in cleaning up `serverutil/perm` and its tests. I believe it's now a pretty clean piece of code and shouldn't trouble us further. I don't see a reason to change it now.

**Comment by adg** [comment] 2017-06-20 21:42
We haven't had any issues with this in a while, so I'll close this. Reopen if you disagree.

**Closed by adg** 2017-06-20 21:42 UTC
Labels: cleanup
