### ISSUE TITLE
all: should not need to have separate key for ann+snapshot@example.com

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#194] opened 2017-02-20 03:47 UTC
Snapshots should be easy to set up, and one way to help is not to require the user's key to be stored twice, a chance for mistakes and skew.

Can KeyServer.Lookup ignore the +snapshot part, at least if a first lookup with it fails or some such?

**Comment by edpin** [comment] 2017-02-22 18:33
@n2vi for final security consideration. 

However, I just realized this wouldn't help anything. For two reasons:

1) Even if the keys diverge, the non-suffixed user will continue to be able to see the snapshots dir entries (metadata), as per the special dirserver treatment. 

2) The only time it would be a problem is if the +snapshot user is trying to access files as the +snapshot user in the +snapshot root and discovers its keys no longer work. Then, even if the keyserver sent the owner's public key to it, its own private key wouldn't decrypt the contents.

What I'm getting to is that implicitly sending the public keys of the owner in response to the +snapshot look up would not help when keys diverge. And it would seem to one paranoid about security that the keyserver is lying.

For these reasons, I now think we shouldn't.

**Comment by n2vi** [comment] 2017-02-23 21:42
At minimum, we need to display a warning to the user at key rotation.   If they're doing it because they believe their old key is weak or compromised, they need to think hard about snapshots.

**Comment by edpin** [comment] 2017-03-02 19:13
I think this is mostly a duplicate of #256 which was closed in favor of #269. 

Tentatively closing this one in favor of #269.

**Closed by edpin** 2017-03-02 19:13 UTC
