### ISSUE TITLE
storage: garbage collection

### ISSUE THREAD

**Issue by n2vi** [upspin/upspin#145] opened 2017-01-24 02:12 UTC
We need some way to recover wasted storage by removing objects that are no longer pointed to from DirEntries.

It is not obvious how to do this without risk of deleting something that is still pointed to from somewhere, in the extreme case only by a hash written on paper.

**Comment by edpin** [comment] 2017-02-22 19:14
This is related to part II of issue #172. Solving that first is probably wise. I added some high level comments on how to do the deletion once we figure out who has the right permission.

It involves the store server collecting usage information from its set of DirServers. Then applying that list against the existing references. 

There's a tradeoff of how fast to collect information and how fast to delete. It could be that we delete when space is low based on some stated maximum or desired capacity and that we collect usage information once a day and keep it around for a week. Refs that do not appear in any dir server's record for 7 days are presumed orphan. Maybe adjust 7 to 21 or 30, etc depending on your site's needs.

**Comment by brunoga** [comment] 2017-03-20 21:41
Are there any temporary workarounds for this? Due the fact that I was experimenting with the server I now have a server with several Gb of garbage that would be great if I could free up.

**Comment by edpin** [comment] 2017-03-21 17:18
Workaround: Use `cmd/upspin tar` to get all your current live  files into a tarball.

Wipe* the server completely and start over, using `cmd/upspin tar -extract` to bring your files back up.

\* The wiping method depends on whether you're running the Storeserver on GCS or on-disk. For on-disk, just `rm -rf upspin/storage` (or whatever you configured it to be). For GCS, it will be something like `gsutil -m rm gs://<bucket-name>/**`

**Comment by brunoga** [comment] 2017-03-21 17:40
That did not quite work. I am getting this after removing the storage dir (and restarting the server. Maybe I should not have done that?):

upspin tar -extract bga.bug-br.org.br.tar
upspin: tar: dir/remote.Put("remote,upspin.bug-br.org.br:443"): item does not exist:
	bga@bug-br.org.br/Codigo Acesso Receita.txt: dir/server.Put:
	client/clientutil.ReadAll:
	client/clientutil.ReadLocation:
	store/server.Get:
	cloud/storage/disk.Download: 5A5F3289C2B80F3A8E58EC66D8084F035395F912BBD1F1BA353ACB4D8610D288

Note I do not really need the files that were there (they were only 2 small files that I have copies with somewhere else), so completely clearing the storage is fine.

also, upspin ls is also failing with a similar error message as above.

**Comment by edpin** [comment] 2017-03-21 17:44
Sorry, I forgot you need to remove the `dirserver-logs` directory as well. Then you'll need to re-create your root.

**Comment by brunoga** [comment] 2017-03-21 17:52
That did the trick. Thanks.

**Comment by n2vi** [comment] 2017-05-17 06:29
See CL 9643 and 9644.     I don't claim those fix this issue, but we needed something to hold us over until the real fix arrives.

**Comment by Splizard** [comment] 2017-06-29 00:08
I would imagine Garbage collection would need to involve reference counting of some kind in order to deal with extreme cases such as a hash written on paper.

**A proposal:**
To my understanding, a call to StoreServer.Put may by chance return a reference to a block already available in storage.
So in order to have garbage collection, the storage server could return a combined encoded reference of (Reference+UniqueID).
This combined reference would point to the same block as (Reference) would.
The Directory Server would be responsible for deleting combined references when they are removed from it's tree. This is achieved by calling StoreServer.Delete(combinedreference).
The Store Server needs to keep a list of Unique ID's per block (added by StoreServer.Put). When StoreServer.Delete is called, it removes a unique ID from the file. When there are no more unique ID's, the file is deleted from the disc.
This can be adapted in a number of ways, the Unique ID could contain a username or the reference counting could be done on the Directory Server.

Consider the hash written on paper. As a user, I have manually interacted with the StoreServer by remotely calling a StoreSever.Put(data), I get the reference(s) back and I write it down on a piece of paper.
I leave this piece of paper in a secure location for an indefinite amount of time.
I find the paper again at some point, remotely call StoreServer.Get(references(s)) and considering that the Server is still operational, I am guaranteed to retrieve my data.

**Comment by adg** [comment] 2017-06-29 23:10
@Splizard How does this proposal accommodate me copying a DirEntry from one tree to another? The StoreServer doesn't see that happening, as no new references are created. But if the entry is deleted from the original directory server, the corresponding references would also disappear.

This is a very hard problem.

**Comment by brunoga** [comment] 2017-06-29 23:53
I do understand the problem of copying a DirEntry from one tree to another but, to me, it looks like the solution is simply changing things to account for that. Is this case I guess it would mean that whenever one copies a DirEntry (assuming it can only be done through a upspin API), the API would have to tell the origin storage server about a new reference being acquired to the entry in question.

Of course, I may simply be overlooking something else relevant here that would make this not work at all.

**Comment by adg** [comment] 2017-06-29 23:58
That raises the question of access control. Who is permitted to increment the ref count for a reference on a given storeserver? Anyone? Just because someone made a copy of my tree, doesn't mean I don't want to collect that data when I delete it.

**Comment by Splizard** [comment] 2017-06-30 00:39
@adg 
The responsibility is on the Directory Server (or person) to keep track of the references they are given. This includes the legality of copying DirEntries on the Server.

A directory server which allows copying in this manner would need to ensure it will only delete a unique DirEntry from the Storage Server.
In the case when the Directory Server removes a file, it could be added to a removal list, they could be added to the list as DirEntries or Blocks (It depends if only files should be able to be copied in this way or individual blocks too).

There would be a goroutine which is slowly scanning through every directory entry on the server, if the goroutine finds a directory entry / block which matches another, it removes the candidate from the removal list. Any entries which are still in the list after they have witnessed two cycles of the goroutine (the entries need to keep track of this) are finally deleted from both the Directory Server and the Storage Server.

The problem with placing responsibility on the Directory Server is when you would like to copy the DirEntry to another Directory Server. 
Consider the paper example from my last comment, I could create a copy of the paper reference and give this to a friend of mine (he is another Directory Server). I am trusted by the Storage Server and I am allowed to delete blocks.
There is no way for me to know if my friend still has the copy without me contacting him. Before I delete the data I can either ask my friend if they still have the reference and he will ask all his friends etc. (he may have given the reference to someone else). My other option is to tell my friend beforehand that there is no guarantee on the references being valid the next day, so he needs to copy the data onto his storage server asap.

**Comment by adg** [comment] 2017-06-30 00:59
> The problem with placing responsibility on the Directory Server is when you would like to copy the DirEntry to another Directory Server.

This is the problem I was referring to, when the direntry is copied to a dirserver that you don't control or even know about (if a person can read a direntry they can copy it).

> There is no way for me to know if my friend still has the copy without me contacting him. Before I delete the data I can either ask my friend if they still have the reference and he will ask all his friends etc. (he may have given the reference to someone else). My other option is to tell my friend beforehand that there is no guarantee on the references being valid the next day, so he needs to copy the data onto his storage server asap.

Agree with all of this, but I don't see a solution in the analogy. One approach is to say to people "if you rely on other people's storeservers then you should expect it to go away".

There are other edge cases, too. For instance, when I write to tree in a dirserver that I don't control, my references are still stored in my store. How does my store know when those files are deleted from the dirserver? What if they aren't deleted by me?

As I said, the problem is a difficult one. A correct solution will involve a number of tradeoffs and will need to be carefully explored in a detailed plan.

**Comment by n2vi** [comment] 2017-06-30 01:38
For the record, here are two proposals made in past discussions of this
problem:

1) Enable readers to make micro-payments per block per month.   When the
storage cost of a block is larger than the accumulated payments over some
period, reap.

2) Assert that each storage server must have an associated list of
authoritative directory servers.  Using the obvious mark sweep algorithm,
garbage collect any blocks not referenced by the trees (including the
snapshot trees) in those directory servers.   Also provide a tool for the
person paying for storage to see how much storage cost is incurred per user.

I implemented #2 a couple different ways but by universal agreement my code
was too ugly and was abandoned.   The algorithm itself is easy, the problem
is how to plumb it safely and cleanly into our existing infrastructure.   I
prefer #1 anyway.

Moreover, I never prepared the convincing, detailed plan that Andrew asks
for.   I'm content to wait for him to do that.

**Comment by adg** [comment] 2017-06-30 01:46
On 30 June 2017 at 11:38, Eric Grosse <notifications@github.com> wrote:

> Moreover, I never prepared the convincing, detailed plan that Andrew asks
> for. I'm content to wait for him to do that.
>

FWIW, I'm not planing on doing this any time soon. I think the project has
higher priorities.

**Comment by adg** [comment] 2017-12-18 05:07
We have this in upspin-audit now. Perhaps we should document it and move the tool to the core repo.

**Comment by robpike** [comment] 2017-12-19 00:42
Closing this, opening https://github.com/upspin/upspin/issues/560

**Closed by robpike** 2017-12-19 00:42 UTC
Labels: feature
